OnlainStore/Views/ViewComponents/CartViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using OnlainStore.Models.Cart;

namespace OnlainStore.Views.ViewComponents;

public class CartViewComponent  : ViewComponent
{
    public IViewComponentResult Invoke()
    {
        var model = new CartVM();
        var qty = 0;
        var price = 0m;
        if (ViewData["cart"] !=null)
        {
            var list = (List<CartVM>)ViewData["cart"];
            foreach (var item in list)
            {
                qty += item.Quantity;
                price += item.Price * item.Quantity;
            }
            model.Quantity = qty;
            model.Price = price;
        }
        else
        {
            model.Quantity = 0;
            model.Price = 0m;
        }
        
        return View("_CartPartial",model);
    }
}

OnlainStore/Views/ViewComponents/CategoryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using OnlainStore.Models.Data;
using OnlainStore.Models.ViewModel.Pages;

namespace OnlainStore.Views.ViewComponents;

public class CategoryViewComponent : ViewComponent
{
    public IViewComponentResult Invoke()
    {
        List<CategoryVM> categoryVMList;
        using (var db = new Db())
        {
            categoryVMList = db.Categories.ToArray()
                .OrderBy(x => x.Sorting)
                .Select(x => new CategoryVM(x))
                .ToList();
        }
        return View("_CategoryMenuPartial",categoryVMList);
    }
   
}

OnlainStore/Views/ViewComponents/SidebarViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using OnlainStore.Models.Data;
using OnlainStore.Models.ViewModel.Pages;

namespace OnlainStore.Views.ViewComponents;

public class SidebarViewComponent : ViewComponent
{
    public IViewComponentResult Invoke()
    {
        SidebarVM model;
        using (var db = new Db())
        {
            var dto = db.Sidebars.Find(2);
            model = new SidebarVM(dto);
        }
        return View("_SidebarMenuPartial",model);
    }
}

OnlainStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<br/>
<br/>
<br/>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Shopping Cart </title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/OnlainStore.styles.css" asp-append-version="true"/>
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.13.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.min.js"></script>
    <script src="https://cdn.ckeditor.com/4.22.1/standard-all/ckeditor.js"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light fixed-top" style="background-color: #e3f2fd;">
    <a class="navbar-brand" href="/">Terekhov Shop</a>
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav me-auto">
                @* @await Component.InvokeAsync("PagesMenuPartial") *@
                @if (User.Identity.Name != null)
                {
                    @Html.ActionLink("Logout", "Logout", "Account", null, htmlAttributes: new { @class = "navbar-text", style = "text-decoration: none" })
                }
                else
                {
                    if (ViewBag.Title == "Login")
                    {
                        <li class="navbar-text"> @Html.ActionLink("Login", "Login", "Account", null, htmlAttributes: new { @class = "active", style = "text-decoration: none" })</li>
                    }
                    else
                    {
                        @Html.ActionLink("Login", "Login", "Account", null, htmlAttributes: new { @class = "navbar-text", style = "text-decoration: none" })
                    }
                }
                @if (User.Identity.Name != null)
                {
                    if (ViewBag.Title == "User Profile")
                    {
                        <li class="active"> @await Component.InvokeAsync("UserNavPart")</li>
                    }
                    else
                    {
                        <li> @await Component.InvokeAsync("UserNavPart")</li>
                    }
                }
            </ul>
            @if (User.Identity.Name != null && User.IsInRole("Admin"))
            {
                <span class="navbar-text">
                    @Html.ActionLink("Admin Area", "Index", "DashBoard", new { area = "Admin" })
                </span>
            }
            else
            {
                if (ViewBag.Title != "Cart Details")
                {
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            @await Component.InvokeAsync("Cart")
                        </li>
                    </ul>
                }
            }
        </div>

    </div>
</nav>
<div class="container body-content" style="margin-top: 25px;">
    <div class="row">
        @if (ViewBag.Title != "User Profile")
        {
            <div class="col-sm-12 col-md-3 list-group">
                @await Component.InvokeAsync("Category")
            </div>
        }
        @if (ViewBag.Sidebar == "Yes")
        {
            <div class="col">
                @RenderBody()
            </div>
            <div class="col-sm-12 col-md-3">
                @* @await Component.InvokeAsync("Sidebar") *@
            </div>
        }
        else
        {
            <div class="col">
                @RenderBody()
            </div>
            <div class="col-sm-12 col-md-3">

            </div>
        }
    </div>
    <hr/>
    <footer>
        <p>&copy; @DateTime.Now.Year - Terekhov Shop</p>
    </footer>
</div>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="https://unpkg.com/dropzone@5/dist/min/dropzone.min.js"></script>
<link rel="stylesheet" href="https://unpkg.com/dropzone@5/dist/min/dropzone.min.css" type="text/css"/>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>